version: "3.5"

services:
  symbiote-ele:
    image: symbioteh2020/symbiote-enablerlogicexample
    depends_on:
      - symbiote-cloudconfig
      - symbiote-rabbitmq
      - symbiote-rap
      - symbiote-rh
    deploy:
     resources:
       limits:
         memory: 350M
    networks: 
      - symbiote
    secrets:
      - source: eleconfig
        target: /home/bootstrap.properties
    environment:
      # - JAVA_HTTP_PROXY=-Dhttp.proxyHost=146.124.225.18 -Dhttp.proxyPort=3128
      # - JAVA_HTTPS_PROXY=-Dhttps.proxyHost=146.124.225.18 -Dhttps.proxyPort=3128
      # - JAVA_SOCKS_PROXY=-DsocksProxyHost=146.124.225.18 -DsocksProxyPort=3128
      # - JAVA_NON_PROXY_HOSTS=-Dhttp.nonProxyHosts=*symbiote-h2020.eu|symbiote-cloudconfig|symbiote-aam
      - _JAVA_OPTIONS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -XX:+PrintFlagsFinal
      - SPRING_BOOT_WAIT_FOR_SERVICES=symbiote-cloudconfig:8888;symbiote-eureka:8761;symbiote-rap:8103;symbiote-rh:8001
secrets:
  eleconfig:
    file: ./EnablerLogicExample/bootstrap.properties
